#!/bin/sh

# ===========================================================================
# lispe, Scheme interpreter.
# ===========================================================================

# This script is used by the author to make the Windows version.

case $# in
	2) lispe_vmaj=$1; lispe_vmin=$2 ;;
	*) echo "$0 major_version minor_version"; exit 0 ;;
esac

lispe_xver=$lispe_vmaj.$lispe_vmin
lispe_wver=$lispe_vmaj$lispe_vmin
lispe_xname=lispe-$lispe_xver
lispe_wname=lispev$lispe_wver
lispe_targz=$lispe_xname.tar.gz
sedmask='s/$//'

show_menu () {
	echo "*********"
	echo " M E N U "
	echo "*********"
	echo "1. Download $lispe_targz"
	echo "2. Compile $lispe_xname"
	echo "3. Make $lispe_wname.zip"
	echo "4. Clean all"
	echo "5. Remove $lispe_targz"
	echo "6. Exit"
}

download_src () {
	if [ ! -f $lispe_targz ]
	then
		wget -c https://jorgicor.niobe.org/lispe/$lispe_targz
		if [ $? -ne 0 ]
		then
			echo "Error downloading $lispe_targz"
		else
			echo "Ok"
		fi
	else
		echo "Ok"
	fi
}

compile_src () {
	tar -xvzf $lispe_targz
	cd $lispe_xname
	./configure --host=i686-w64-mingw32
	make
	cd ..
}

make_zip () {
	mkdir $lispe_wname
	cd $lispe_wname
	cp ../$lispe_xname/src/lispe.exe .
	# groff -m man -T html ../$lispe_xname/doc/lispe.1 > lispe.html
	cp ../$lispe_xname/COPYING copying.txt
	cp ../$lispe_xname/README readme.txt
	cp ../$lispe_xname/NEWS news.txt
	for i in *.txt
	do
		sed $sedmask $i > tmp.txt
		rm $i
		mv tmp.txt $i
	done
	i686-w64-mingw32-strip lispe.exe
	cd ..
	zip -r $lispe_wname.zip $lispe_wname
}

clean_all () {
	rm -r $lispe_xname
	rm -r $lispe_wname
}

remove_src () {
	rm $lispe_targz
}

read_option () {
	local choice
	echo -n "Select option: "
	read choice
	case $choice in
		1) download_src ;;
		2) compile_src ;;
		3) make_zip ;;
		4) clean_all ;;
		5) remove_src ;;
		6) exit 0 ;;
		*) echo "Wrong option" ;;
	esac
}

while true
do
	show_menu
	read_option
done
